### PR TITLE
Typo fixes in README.md.

### PR DESCRIPTION
**Pull request by Rafael-Baltazar**
3, added ','.
9, added ','.
23, added ',', removed 'just'.
25, added ','.
27, added ','.
28, edited 'adding' to 'add a'.
merged 27 with 28.
31(30 after merge), added ',' twice.
split 31 into 31 and 32.
36, added ','.
38, edited 'disseration' to 'dissertation', added ',' twice, edited 'where' to 'wherever', added '.'.
split 38 into 38 and 39.
49(50 after split), edited 'define' to 'defining'.
split 49(50 after 1 split) into 49(50 after split) and 50(51 after split).
52(54 after split), added ',' twice, removed 'start'.
split 52(54 after 2 split) into 52(54 after split), 53(55 after split) and 54(56 after split).
split 58(62 after 4 split) into 58(62 after split) and 59(63 after split).
split 61(66 after 5 split) into 61(66 after split) and 62(67 after split).
64(70 after 6 split), edited 'To create the final pdf you have two ways to do it' to 'You have two ways to create the final pdf'.
73, added ','.
66(73 after split), removed 'you' and 'to'.
split 66(73 after 7 split) into 66(73 after split) and 67(74 after split).
70(78 after split), added ','.
75(83 after split), added ','.
81(89 after split), edited 'a bit its structure' to 'its structure a bit'.
split 81(89 after 8 split) into 81(89 after split) and 82(90 after split).
83(92 after split), added ',', edited 'a' to 'an'.

### CODE REVIEW

**Comment by Rafael-Baltazar** [comment]
Closes #1

**Comment by samfcmc** [comment]
Your pull requests has conflicts. You worked on a fork that is behind the original one. Can you sync your fork with mine and make that pull request again?
Thanks

**Comment by Rafael-Baltazar** [comment]
Before I do that, do you want .tex files to have each sentence in a separate line (like I have) or each paragraph in the same line (like you have)?

**Comment by samfcmc** [comment]
You can put each sentence in a separate line. Sometimes I put everything in the same line because the way of my text editor handles that. But yes do it.

**Comment by samfcmc** [comment]
Just make sure that you sync with this repo before you submit your pull request

**Comment by Rafael-Baltazar** [comment]
It is now up-to-date. I used separate lines for each sentence.

**Pull request merged**
